{% set name = "pytest-regressions" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4c30064e0923929012c94f5d6f35205be06fd8709c7f0dba0228e05c460af05e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<39]

requirements:
  host:
    - pip
    - python 
    - wheel
    - setuptools
    - setuptools_scm
  run:
    - python
    - pytest >=6.2.0
    - pytest-datadir >=1.2.0
    - pyyaml

test:
  source_files:
    - tests
  imports:
    - pytest_regressions
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')
    - pytest -v tests
  requires:
    - pip
    - matplotlib-base
    - {{ pin_compatible('numpy') }}
    - pandas
    - pillow

about:
  home: https://github.com/ESSS/pytest-regressions
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Easy to use fixtures to write regression tests.
  description: Easy to use fixtures to write regression tests.
  doc_url: https://pytest-regressions.readthedocs.io
  dev_url: https://github.com/ESSS/pytest-regressions

extra:
  recipe-maintainers:
    - alexandrebbruno
    - igortg
    - nicoddemus
    - tadeu
